# Generated by Django 4.0 on 2021-12-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email_id',
            field=models.EmailField(max_length=251),
        ),
    ]
